### ISSUE TITLE
Thundergrass is using Ossidroot blocks

### ISSUE THREAD

**Issue by brasscrest** [Sinhika/ashenwheat#9]
Version: ashenwheat-1.19.2-6.1.0.0

Growing Thundergrass is using the models for Ossidroot. I believe that the issue is in the blockstate JSON (assets\ashenwheat\blockstates\thunder_grass_crop.json), which is pointing at the Ossidroot models.

**Comment by Sinhika** [comment]
Fixed as of release 1.19.2-6.1.0.1
